version: '3'

services:
  php70:
    volumes:
    - ./workspace:/data
  php56:
    volumes:
    - ./workspace:/data
  php71:
    volumes:
    - ./workspace:/data
  php72:
    volumes:
    - ./workspace:/data
  php73:
    volumes:
    - ./workspace:/data
  web:
    volumes:
    - ./workspace:/data:ro
