
db:
    image: percona
    volumes:
        - ./mysql:/var/lib/mysql
    env_file: conf/mysql
    ports:
        - 3306:3306

redis:
    image: redis

mailcatcher:
    image: schickling/mailcatcher

blackfire:
    image: blackfire/blackfire
    env_file:
        - conf/blackfire

php5:
    build: php5
    volumes:
        - ./workspace:/data
        - ${HOME}/.ssh/id_rsa:/data/.ssh/id_rsa:ro
    links:
        - db
        - mailcatcher
        - redis
        - blackfire

php7:
    build: php7
    volumes:
        - ./workspace:/data
        - ${HOME}/.ssh/id_rsa:/data/.ssh/id_rsa:ro
    links:
        - db
        - mailcatcher
        - redis
        - blackfire

web:
    build: nginx
    volumes:
        - ./workspace:/data:ro
    links:
        - php5:fpm

        - php5:fpm5
        - php7:fpm7
        - mailcatcher
    ports:
        - 80:80
        - 443:433

