
db:
    image: percona
    volumes:
        - ./mysql:/var/lib/mysql
    env_file: conf/mysql
    ports:
        - 3306:3306

redis:
    image: redis

mailcatcher:
    image: schickling/mailcatcher

php5:
    build: php5
    volumes:
        - ./workspace:/data
    links:
        - db
        - mailcatcher
        - redis

php7:
    build: php7
    volumes:
        - ./workspace:/data
    links:
        - db
        - mailcatcher
        - redis

web:
    build: nginx
    volumes:
        - ./workspace:/data:ro
    links:
        - php5:fpm

        - php5:fpm5
        - php7:fpm7

        - mailcatcher
    ports:
        - 80:80
        - 443:443

