version: '2'
services:
  blackfire:
    env_file:
        - ./conf/blackfire
    image: blackfire/blackfire
    network_mode: bridge

  php5:
      links:
          - blackfire
  php7:
      links:
          - blackfire
