version: '3'

networks:
  frontend:
  backend:
  databases:

volumes:
  dockerdev-mysql-volume:
    external: true
  dockerdev-workspace-volume:
    external: true

services:
  db:
    container_name: dockerdev-db
    image: percona
    volumes:
      - ./conf.d/mysql/my.cnf:/etc/my.cnf.d/development.cnf:ro
      - dockerdev-mysql-volume:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD
    networks: 
      - databases
    ports:
      - 127.0.0.1:3306:3306

  mailcatch:
    image: mailhog/mailhog
    networks: 
      - backend
    
  php56:
    build:
      context: build/dist/php
      args:
        - FROM_TAG=php5-fpm
    volumes:
      - dockerdev-workspace-volume:/data
    links:
      - db
      - mailcatch
      - redis
    networks:
      - backend
      - databases
  php70:
    build:
      context: build/dist/php
      args:
        - FROM_TAG=php7-fpm
    volumes:
      - dockerdev-workspace-volume:/data
    links:
      - db
      - mailcatch
      - redis
    networks:
      - backend
      - databases
  php71:
    build:
      context: build/dist/php
      args:
        - FROM_TAG=php71-fpm
    volumes:
      - dockerdev-workspace-volume:/data
    links:
      - db
      - mailcatch
      - redis
    networks:
      - backend
      - databases
  php72:
    build:
      context: build/dist/php
      args:
        - FROM_TAG=php72-fpm
    volumes:
      - dockerdev-workspace-volume:/data
    links:
      - db
      - mailcatch
      - redis
    networks:
      - backend
      - databases
  php73:
    build:
      context: build/dist/php
      args:
        - FROM_TAG=php73-fpm
    volumes:
      - dockerdev-workspace-volume:/data
    links:
      - db
      - mailcatch
      - redis
    networks:
      - backend
      - databases

  redis:
    image: redis:alpine
    networks:
      - databases

  web:
    build:
      context: build/dist/web
    volumes:
      - dockerdev-workspace-volume:/data:ro
    environment:
      - DOMAINSUFFIX
    links:
      - mailcatch
      - php71:fpm
      - php70:fpm70
      - php56:fpm56
      - php71:fpm71
      - php72:fpm72
      - php73:fpm73
    networks:
      - frontend
      - backend
  ssl:
    build:
      context: build/dist/ssl
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend

